---
# tasks file for elasticsearch
- include_tasks: asserts.yml
- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- name: Set elasticsearch.yml
  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: 0640
    owner: root
    group: elasticsearch
      #  notify: Restart elasticsearch
- name: Set Xms
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xms'
    line: "-Xms{{ es_heap_space }}"
- name: Set Xmx
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx'
    line: "-Xmx{{ es_heap_space }}"

- name: Test keystore
  stat:
    path: /usr/share/elasticsearch/config/elasticsearch.keystore
  register: __keystore
- name: Init keystore
  command: elasticsearch-keystore create
  when: not __keystore.stat.exists

- name: Get installed packages
  package_facts:
    manager: "auto"
- name: open firwall port for elasticsearch
  ufw:
    rule: allow
    direction: in
    src: "{{ es_ufw_from }}"
    to_port: "{{ es_port }}"
  when: "'ufw' in ansible_facts.packages"
